# Generated by Django 6.1 on 2026-08-08 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marksheet',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='marksheet',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marksheet',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='The teacher who approved or rejected this marksheet.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marksheet_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marksheet',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
