# Generated by Django 6.1 on 2026-08-08 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_marksheet_rejection_reason_marksheet_reviewed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerSheetReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='e.g. "Biology Midterm"', max_length=150)),
                ('image', models.ImageField(upload_to='answer_sheets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transcription', models.TextField(blank=True)),
                ('overall_feedback', models.TextField(blank=True)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('mistakes', models.JSONField(blank=True, default=list)),
                ('improvement_suggestions', models.TextField(blank=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_sheet_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
