# Generated by Django 6.1 on 2026-08-08 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_answersheetreview'),
        ('courses', '0002_lessonresource_quiz_quizattempt_quizquestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VivaSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed')], default='in_progress', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('verdict', models.CharField(blank=True, choices=[('strong', 'Genuine understanding'), ('developing', 'Developing understanding'), ('rote', 'Memorized, not understood'), ('weak', 'Significant gaps')], max_length=12)),
                ('verdict_summary', models.TextField(blank=True)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('gaps', models.JSONField(blank=True, default=list)),
                ('suggestions', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viva_sessions', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viva_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VivaTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('question', models.TextField()),
                ('probe_reason', models.CharField(blank=True, help_text='Why the AI is asking this — shown as a small hint.', max_length=200)),
                ('answer', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='ai.vivasession')),
            ],
            options={
                'ordering': ['round_number'],
                'unique_together': {('session', 'round_number')},
            },
        ),
    ]
